export default defineEventHandler((event) => {
    const query = getQuery(event);
    return {
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus pellentesque, urna ut feugiat dapibus, nisl tellus hendrerit purus, id maximus turpis nisi a erat. Maecenas odio dolor, eleifend id orci vel, porta maximus mi. Vivamus faucibus sodales tortor, id blandit nunc laoreet ut. Quisque nisi magna, luctus eget tellus et, laoreet eleifend diam. Donec bibendum ornare libero, vitae accumsan libero. Cras a quam sit amet augue sollicitudin condimentum vel id ligula. Etiam nec enim vel odio cursus fringilla. Cras ullamcorper nisl sed arcu semper, non condimentum sem commodo.\n' +
            '\n' +
            'Morbi blandit, urna id fermentum rhoncus, mi lectus posuere dui, vitae pulvinar metus felis tempor velit. Duis vitae laoreet neque, quis tincidunt metus. Proin porttitor suscipit urna, at elementum turpis tincidunt ultrices. Vestibulum sed est placerat, luctus ipsum euismod, malesuada ante. Quisque consequat commodo accumsan. Integer lectus quam, ullamcorper non orci ac, suscipit convallis tortor. Phasellus molestie, massa sit amet interdum facilisis, felis ex mattis nisi, a auctor mi nisi quis ligula. Ut finibus risus lorem, eu luctus urna viverra eu. Pellentesque a eros est. Vestibulum aliquet diam ut dolor luctus, sed bibendum sem sodales. Aenean nec ornare purus. Sed nisi ante, dictum id hendrerit eu, auctor ac sapien. In a quam felis. In hac habitasse platea dictumst. Morbi rhoncus porta diam, ut maximus libero congue sit amet.\n' +
            '\n' +
            'Pellentesque blandit laoreet justo, ut tempor felis gravida quis. Nunc eleifend id dui et feugiat. Morbi ac orci ligula. Fusce eleifend massa at ligula lacinia, sed efficitur nunc elementum. Pellentesque facilisis ut enim at pulvinar. Vestibulum dapibus sodales fermentum. Nam at dolor vitae arcu efficitur malesuada. Fusce quis tellus lacus. Ut erat risus, consectetur et urna vel, commodo vestibulum nunc. Vivamus pulvinar porta purus eu porttitor. Sed dapibus lacinia eros quis semper. Nunc vehicula iaculis tincidunt. Praesent pharetra ac lacus molestie semper. Nulla bibendum, velit in pulvinar ultricies, eros lacus tempor sem, eu mollis purus velit at tortor. Nulla sed ultricies felis.\n' +
            '\n' +
            'Maecenas at erat id ante laoreet accumsan. Sed eget dolor metus. Phasellus id urna sit amet risus vulputate tempus. Cras eget erat ac elit aliquam bibendum a ut justo. Donec id blandit enim. Morbi pellentesque erat non gravida tincidunt. In sit amet quam orci. Nullam vel sagittis nulla. Proin sed mattis nulla, sed vestibulum libero. Vestibulum eu lacus sagittis, pulvinar nisl vitae, condimentum ipsum. Praesent iaculis lorem ipsum, eu finibus velit sagittis sed. Curabitur quis ipsum neque. Vivamus tempor sapien et pellentesque lacinia. Ut congue sapien vitae diam mollis, eu consectetur elit consequat.\n' +
            '\n' +
            'Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent sodales mauris commodo luctus tempor. Cras ac lectus a odio cursus venenatis. Fusce sit amet dui porttitor, dapibus arcu a, condimentum nunc. Interdum et malesuada fames ac ante ipsum primis in faucibus. Integer tincidunt mi eget arcu vulputate, a porttitor ipsum pharetra. Duis odio nunc, bibendum sed tortor vel, interdum vehicula felis. Sed semper, turpis ac porta venenatis, elit orci aliquet metus, vitae vestibulum massa lectus sit amet nisl.\n' +
            '\n' +
            `${query.lesson}-${query.step}`
    }
})
